[proxy]
type = "tls" # has to be either "tcp" or "tls"
source = "127.0.0.1:4500"
destination = "127.0.0.1:8888"

[tls]
disable_automatic = false # make this true to turn off automatic certs fetching and renewals from Letsencrypt
domain = "example.com" # domains for automatic https
certs_path = "/path/to/store/certs" # path where the automatic letsencrypt certs are stored
cloudflare_api_token = "auth-token" # API token for cloudflare
email = "hello@example.com" # Email for letsencrypt
check_for_expiry = "240h" # Duration to check for expiry and renew. Default is 10days.
# Only set these if you want to provide certs manually, i.e disable_automatic is true.
cert = "/path/to/cert"
key = "/path/to/key"